name: تحليل الذهب والأسواق

on:
  schedule:
    # يعمل الساعة 8 صباحاً بتوقيت UTC، أي 11 صباحاً بتوقيت بغداد
    - cron: '0 8 * * *'
  workflow_dispatch: # يسمح بالتشغيل اليدوي أيضاً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: سحب كود المستودع
        uses: actions/checkout@v3

      - name: إعداد بيئة بايثون
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: تثبيت المكتبات المطلوبة
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.26.4 pandas==2.2.2 pandas-ta yfinance requests

      - name: تشغيل سكربت تحليل الذهب
        run: python gold_analyzer.py

      - name: تشغيل سكربت تحليل VIX
        run: python get_vix.py

      - name: تشغيل سكربت تحليل العائدات
        run: python get_yields.py

      - name: حفظ وتحديث ملفات التحليل
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "تحديث تلقائي لبيانات التحليل"
          # نحدد كل الملفات ليتم تحديثها
          file_pattern: analysis.json vix_data.json yield_data.json
